name: extreme_antarctic_ars_python
channels:
  - defaults
dependencies:
  # core languages
  - python=3.12

  # python packages
  - numpy=2.4.*
  - pandas=3.0.*
  - xarray=2026.2.*
  - tqdm
  - huggingface_hub=1.9.*
  - seaborn=0.13.*
  - matplotlib=3.10.*
  - scipy=1.17.*
  - xgboost=3.0.*
  - ipython
  - scikit-learn=1.8.*
  - ipykernel
  - shap=0.48.*
  - rpy2
  - pip
  
  - pip:
    - earthaccess==0.16.*
    - jupyterlab_myst
    - jupyter-keepalive
    - mystmd
    - git+https://github.com/jbbutler/antarctic_AR_dataset.git # artools package
