
library(quantreg);
library(foreign);
source("Y:/Extremes/Programs website/Updated/Programs/R-progs.R")



#Y is generated according to a t-model.
#X is generated by sampling with replacement from var_data.txt 




################### Section I: Preliminary Programs ###############################

######################## generate data for i-th monte-carlo ####################################


gen.data<- function(Xt, nn, DF) {
	ind	<- sample(1:1000, nn, replace=T);
    	XX	<- as.matrix(Xt[ind,]);
	YY	<-  XX%*%rep(1, 4) + .07*rt(nn, DF);
	return(cbind(YY,XX) ); 
	}



########################### Monte-Carlo Function #####






monte.cov<- function(Xt, nn = 500, alpha = .10, filen, filen.bias, DF, ...) {

# generate data ; 
 
datt		<- gen.data(Xt, nn, DF=DF);  
YY		<- datt[,1]; 
XX		<- datt[,-c(1,2)];
X1.pos		<- (XX[ ,1] >= 0) * XX[ ,1];
X1.neg		<- -(XX[ ,1] <= 0) * XX[ ,1];
X2.pos		<- (XX[ ,2] >= 0) * XX[ ,2];
X2.neg		<- -(XX[ ,2] <= 0) * XX[ ,2];
X3.pos		<- (XX[ ,3] >= 0) * XX[ ,3];
X3.neg		<- -(XX[ ,3] <= 0) * XX[ ,3];
#X1		<- XX[ ,1];
#X2		<- XX[ ,2];
 
# QR fits;

taus		<- c(.01, .10, .25, .50, .75, .90, .99);
taus		<- c(.01, .05, .10, .25, .50);
formula 	<- YY ~ X1.pos  + X2.pos + X3.pos + X1.neg  + X2.neg  + X3.neg;  
p 		<- 7;

cov.centr	<- NULL;
miss.centr	<- NULL;
cov.extr	<- NULL;
miss.extr	<- NULL;

for (tau in taus) {; 
	fit		<- rq(formula, tau = tau);

# central inference


	centr		<- summary.rq(fit, se = "ker");
	misc		<- c(centr$coefficients[1,1] - 1- .07*qt(tau,DF) ,  centr$coefficients[3,1] - 1 );
 	covc		<- c( I( centr$coefficients[1,1] + qnorm(alpha/2)*centr$coefficients[1,2] < 1 + .07*qt(tau,DF) )* I ( 1 + .07*qt(tau,DF) < centr$coefficients[1,1] + qnorm(1-alpha/2)*centr$coefficients[1,2]), 
				I( centr$coefficients[3,1] + qnorm(alpha/2)*centr$coefficients[3,2] < 1)* I ( 1 < centr$coefficients[3,1] + qnorm(1 - alpha/2)*centr$coefficients[3,2]));

	cov.centr	<- c(cov.centr, covc);
	miss.centr	<- c(miss.centr, misc);


# extreme inference


	extr		<- summary.rq.extreme(fit, subsample.fraction=.2, R=200, method = "br", alpha = .10, spacing = 5+p);
	mise		<- c(extr$coefficients[1,5] - 1 - .07*qt(tau,DF),  extr$coefficients[3,5] - 1);
	cove		<- c( I(extr$coefficients[1,3] < 1 + .07*qt(tau,DF) )* I ( 1 + .07*qt(tau, DF)< extr$coefficients[1,4]), I(extr$coefficients[3,3] < 1)* I (1< extr$coefficients[3,4]));

	cov.extr	<- c(cov.extr, cove);
	miss.extr	<- c(miss.extr, mise);
	};

write.table(t(c(cov.extr, cov.centr)),   file=filen,      sep="  ", append=T, row.names = FALSE, col.names = FALSE);
write.table(t(c(miss.extr, miss.centr)), file=filen.bias, sep="  ", append=T, row.names = FALSE, col.names = FALSE);


}


########################### Main Program #####


# Read VaR data set;

var_data 	<- read.table("Y:/Extremes/Programs website/Updated/Data/var_data.txt");
Y		<- var_data[1528:2527, 5];
Xt		<- var_data[1528:2527, 1:4];


# Create files for intermediate results;

filenA		<-  "Y:/Extremes/Programs website/Updated/Results/nn500.CASEA.HS.run8.central.ker.txt"
filen.biasA	<-  "Y:/Extremes/Programs website/Updated/Results/nn500.CASEA.HS.BiasAnalysis.run8.central.ker.txt"
filenB		<-  "Y:/Extremes/Programs website/Updated/Results/nn500.CASEB.HS.run8.central.ker.txt"
filen.biasB	<-  "Y:/Extremes/Programs website/Updated/Results/nn500.CASEB.HS.BiasAnalysis.run8.central.ker.txt"
filenC		<-  "Y:/Extremes/Programs website/Updated/Results/nn500.CASEC.HS.run8.central.ker.txt"
filen.biasC	<-  "Y:/Extremes/Programs website/Updated/Results/nn500.CASEC.HS.BiasAnalysis.run8.central.ker.txt"

# Monte Carlo

set.seed(888);
nn		<- 500;
reps		<- 1000;
alpha		<- .10;

# t-1 distribution;

now		<- proc.time(); 
for(i in 1:reps) {;
	monte.cov(Xt, nn, alpha, filenA, filen.biasA, DF=1);
	}; 
speed 		<- (proc.time()-now)/3600;


# t-3 distribution;
now		<- proc.time(); 
for(i in 1:reps) {;
	monte.cov(Xt, nn, alpha, filenB, filen.biasB, DF=3);
	}; 
speed 		<- (proc.time()-now)/3600;

# t-30 distribution;
now		<- proc.time(); 
for(i in 1:reps) {;
	monte.cov(Xt, nn, alpha, filenC, filen.biasC, DF=30);
	}; 
speed 		<- (proc.time()-now)/3600;


# Tables of results:

volA	<- apply(read.table(filenA),2, mean)
volB	<- apply(read.table(filenB),2, mean)
volC	<- apply(read.table(filenC),2, mean)

taus	<- c(.01, .05,  .10, .25, .50);

postscript("Y:/Extremes/Programs website/Updated/Results/MCresultABC.central.spacing5.ker.eps",horizontal=F,pointsize=9,width=6,height=8)

par(mfrow=c(3,2), lab=c(10,10,10))

plot(range(taus), range(0,1), type="n", ylim=c(0,1), xlim=c(0, .5), ylab="Coverage", xlab=expression(tau), main="A. t(1)-disturbance: Coverage for Intercept", lwd=2)
lines( taus, volA[seq(1,10, by=2)], type="l", lty=1, lwd=2, col=4)
lines( taus, volA[seq(11,20, by=2)], type="l", lty=4, lwd=2, col=2)
abline(h=.9, col=1, lwd=2, lty=2)
typ.names <- c("Extremal ", "Central", "Nominal 90%")
legend(.05, .4, legend = typ.names, lty = c(1,4,2), col=c(4,2,1), bty="no", lwd=2)

plot( range(taus), range(0,1), type="n", ylim=c(0,1), xlim=c(0, .5), ylab="Coverage", xlab=expression(tau), main="A. t(1)-disturbance: Coverage for Slopes", lwd=2)
lines( taus, volA[seq(2,10, by=2)], type="l", lty=1, lwd=2, col=4)
lines( taus, volA[seq(12,20, by=2)], type="l", lty=4, lwd=2, col=2)
abline(h=.9, col=1, lwd=2, lty=2)
typ.names <- c("Extremal ", "Central", "Nominal 90%")
legend(.05, .4, legend = typ.names, lty = c(1,4,2), col=c(4,2,1), bty="no", lwd=2)


plot( range(taus), range(0,1), type="n", ylim=c(0,1), xlim=c(0, .5), ylab="Coverage", xlab=expression(tau), main="B. t(3)-disturbance: Coverage for Intercept", lwd=2)
lines( taus, volB[seq(1,10, by=2)], type="l", lty=1, lwd=2, col=4)
lines( taus, volB[seq(11,20, by=2)], type="l", lty=4, lwd=2, col=2)
abline(h=.9, col=1, lwd=2, lty=2)
typ.names <- c("Extremal ", "Central", "Nominal 90%")
legend(.05, .4, legend = typ.names, lty = c(1,4,2), col=c(4,2,1), bty="no", lwd=2)



plot( range(taus), range(0,1), type="n", ylim=c(0,1), xlim=c(0, .5), ylab="Coverage", xlab=expression(tau), main="B. t(3)-disturbance: Coverage for Slopes", lwd=2)
lines( taus, volB[seq(2,10, by=2)], type="l", lty=1, lwd=2, col=4)
lines( taus, volB[seq(12,20, by=2)], type="l", lty=4, lwd=2, col=2)
abline(h=.9, col=1, lwd=2, lty=2)
typ.names <- c("Extremal ", "Central", "Nominal 90%")
legend(.05, .4, legend = typ.names, lty = c(1,4,2), col=c(4,2,1), bty="no", lwd=2)



plot( range(taus), range(0,1), type="n", ylim=c(0,1), xlim=c(0, .5), ylab="Coverage", xlab=expression(tau), main="C. t(30)-disturbance: Coverage for Intercept", lwd=2)
lines( taus, volC[seq(1,10, by=2)], type="l", lty=1, lwd=2, col=4)
lines( taus, volC[seq(11,20, by=2)], type="l", lty=4, lwd=2, col=2)
abline(h=.9, col=1, lwd=2, lty=2)
typ.names <- c("Extremal ", "Central", "Nominal 90%")
legend(.05, .4, legend = typ.names, lty = c(1,4,2), col=c(4,2,1), bty="no", lwd=2)


plot( range(taus), range(0,1), type="n", ylim=c(0,1), xlim=c(0, .5), ylab="Coverage", xlab=expression(tau), main="C. t(30)-disturbance: Coverage for Slopes", lwd=2)
lines( taus, volC[seq(2,10, by=2)], type="l", lty=1, lwd=2, col=4)
lines( taus, volC[seq(12,20, by=2)], type="l", lty=4, lwd=2, col=2)
abline(h=.9, col=1, lwd=2, lty=2)
typ.names <- c("Extremal ", "Central", "Nominal 90%")
legend(.05, .4, legend = typ.names, lty = c(1,4,2), col=c(4,2,1), bty="no", lwd=2)



dev.off();






plot(apply(read.table(filenA),2, mean));


apply(read.table(filenB),2, mean);
apply(read.table(filenC),2, mean);


medad<- function(x){ median(abs(x))} 
absmed<- function(x){ abs(median(x))} 

volA		<- apply(read.table(filen.biasA),2, medad)
volB		<- apply(read.table(filen.biasB),2, medad)
volC		<- apply(read.table(filen.biasC),2, medad)




postscript("Y:/Extremes/Programs website/Updated/Results/MC.Forecast.resultABC.ps",horizontal=F,pointsize=9,width=7.0,height=7.0)

par(mfrow=c(3,2), lab=c(10,10,10))

xlab<- expression(tau)
ylab<- "Median Abs Deviation"
xlim<- c(0.005, .1)
ylim<- c(.5,1.2)

plot( range(.005,.1), range(.5,1.5), type="n", xlim=xlim, ylim=ylim, ylab=ylab, xlab=xlab, main="A. t(1)-disturbance: Estimating Intercept", lwd=2)
lines( taus, volA[seq(1,8, by=2)]/volA[seq(9,16, by=2)], type="l", lty=2, lwd=2, col=3)
typ.names <- c("Ratio of MAD of Bias-Corrected QR \n to MAD of QR")
abline(h=1, col=1, lwd=2, lty=1)
legend(.025, .7, legend = typ.names, lty = c(2), col=c(3), bty="no", lwd=2)


plot( range(.005,.1), range(0,60), type="n", xlim=xlim, ylim=ylim, ylab=ylab, xlab=xlab, main="A. t(1)-disturbance: Estimating Slopes", lwd=2)
lines( taus, volA[seq(2,8, by=2)]/volA[seq(10,16, by=2)], type="l", lty=2, lwd=2, col=3)
typ.names <- c("Ratio of MAD of Bias-Corrected QR \n to MAD of QR")
abline(h=1, col=1, lwd=2, lty=1)
legend(.025, .7, legend = typ.names, lty = c(2), col=c(3), bty="no", lwd=2)


plot( range(.005,.1), range(0,60), type="n", xlim=xlim, ylim=ylim, ylab=ylab, xlab=xlab, main="B. t(3)-disturbance: Estimating Intercept", lwd=2)
lines( taus, volB[seq(1,8, by=2)]/volB[seq(9,16, by=2)], type="l", lty=2, lwd=2, col=3)
typ.names <- c("Ratio of MAD of Bias-Corrected QR \n to MAD of QR")
abline(h=1, col=1, lwd=2, lty=1)
legend(.025, .7, legend = typ.names, lty = c(2), col=c(3), bty="no", lwd=2)

plot( range(.005,.1), range(0,60), type="n", xlim=xlim, ylim=ylim, ylab=ylab, xlab=xlab, main="B. t(3)-disturbance: Estimating Slopes", lwd=2)
lines( taus, volB[seq(2,8, by=2)]/volB[seq(10,16, by=2)], type="l", lty=2, lwd=2, col=3)
typ.names <- c("Ratio of MAD of Bias-Corrected QR \n to MAD of QR")
abline(h=1, col=1, lwd=2, lty=1)
legend(.025, .7, legend = typ.names, lty = c(2), col=c(3), bty="no", lwd=2)


plot( range(.005,.1), range(0,60), type="n", xlim=xlim, ylim=ylim, ylab=ylab, xlab=xlab, main="B. t(30)-disturbance: Estimating Intercept", lwd=2)
lines( taus, volC[seq(1,8, by=2)]/volC[seq(9,16, by=2)], type="l", lty=2, lwd=2, col=3)
typ.names <- c("Ratio of MAD of Bias-Corrected QR \n to MAD of QR")
abline(h=1, col=1, lwd=2, lty=1)
legend(.025, .7, legend = typ.names, lty = c(2), col=c(3), bty="no", lwd=2)

plot( range(.005,.1), range(0,60), type="n", xlim=xlim, ylim=ylim, ylab=ylab, xlab=xlab, main="B. t(30)-disturbance: Estimating Slopes", lwd=2)
lines( taus, volC[seq(2,8, by=2)]/volC[seq(10,16, by=2)], type="l", lty=2, lwd=2, col=3)
typ.names <- c("Ratio of MAD of Bias-Corrected QR \n to MAD of QR")
abline(h=1, col=1, lwd=2, lty=1)
legend(.025, .7, legend = typ.names, lty = c(2), col=c(3), bty="no", lwd=2)

dev.off();






tsplot(abs(mmmB[1:8])/ abs(mmmB[9:16]))

